version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "joevanstack"
s3_bucket = "joevanbucket"
s3_prefix = "joevanstack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND"
