service: hello-world

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: functions/hello-world.function
    events:
    - http:
        path: hello
        method: get

plugins:
  - serverless-offline